ANIMAL_LABEL_DICT = {
                    'butterfly': 0,
                    'cat': 1,
                    'chicken': 2,
                    'cow': 3,
                    'dog': 4,
                    'elephant': 5,
                    'horse': 6,
                    'sheep': 7,
                    'spider': 8,
                    'squirrel': 9,
                    'zebra': 10,
                    'rhino': 11,
                    'buffalo': 12}

REVERSE_ANIMAL_DICT = { 0: 'butterfly',
                        1: 'cat',
                        2: 'chicken',
                        3: 'cow',
                        4: 'dog',
                        5: 'elephant',
                        6: 'horse',
                        7: 'sheep',
                        8: 'spider',
                        9: 'squirrel',
                        10: 'zebra',
                        11: 'rhino',
                        12: 'buffalo'}
